const folderData = {
    "projects": [
        {
            "id": "browser-digital-hygiene",
            "name": "Browser Digital Hygiene Score Web App",
            "folder": "1. Browser Digital Hygiene Score Web App",
            "path": "1. Browser Digital Hygiene Score Web App",
            "viewer": "viewer.html?project=browser-digital-hygiene",
            "description": "Web-based security assessment tool that evaluates browser hygiene, HTTPS configuration, and privacy risks.",
            "files": [
                "index.html",
                "script.js",
                "style.css"
            ]
        },
        {
            "id": "password-checker",
            "name": "Password Strength & Leak Checker",
            "folder": "2. Password Strength & Leak Checker",
            "path": "2. Password Strength & Leak Checker",
            "viewer": "viewer.html?project=password-checker",
            "description": "Password analysis web app that evaluates strength, complexity, and exposure to leaked credentials.",
            "files": [
                "index.html",
                "script.js",
                "splash.html",
                "style.css"
            ]
        },
        {
            "id": "password-vault",
            "name": "Password Vault",
            "folder": "3. Password Vault",
            "path": "3. Password Vault",
            "viewer": "viewer.html?project=password-vault",
            "description": "Secure password management prototype with offline storage, encryption, and credential management.",
            "files": [
                "add_entry.html",
                "manifest.json",
                "style.css",
                "sw.js",
                "vault-core.js",
                "vault.html",
                "welcome.html"
            ]
        },
        {
            "id": "cybersecurity-dashboard",
            "name": "Cybersecurity Monitoring Dashboard",
            "folder": "4. PowerBI1_Cybersecurity_Monitoring_Dashboard",
            "path": "4. PowerBI1_Cybersecurity_Monitoring_Dashboard",
            "viewer": "viewer.html?project=cybersecurity-dashboard",
            "description": "Power BI cybersecurity dashboard assets and demonstration media for security operations analytics.",
            "files": [
                "Cybersecurity Monitoring Dashboard.png",
                "Cybersecurity_Dashboard_Demo.mp4"
            ]
        },
        {
            "id": "sentiment-analysis",
            "name": "Sentiment Analysis Dashboard",
            "folder": "5. PowerBI2_Sentiment_Analysis",
            "path": "5. PowerBI2_Sentiment_Analysis",
            "viewer": "viewer.html?project=sentiment-analysis",
            "description": "Sentiment analysis dashboard dataset and visual assets for customer insights and trend analysis.",
            "files": [
                "Sentiment_Analysis_Dashboard.png",
                "sentiment_data.csv"
            ]
        },
        {
            "id": "smart-city",
            "name": "Smart City Intelligence & Predictive Analytics Platform",
            "folder": "6. PowerBI3_Smart City Intelligence & Predictive Analytics Platform",
            "path": "6. PowerBI3_Smart City Intelligence & Predictive Analytics Platform",
            "viewer": "viewer.html?project=smart-city",
            "description": "Urban analytics dashboard source files and datasets for smart city monitoring and predictive planning.",
            "files": [
                "Dim_ComplaintCategory.csv",
                "Dim_EnergySource.csv",
                "Dim_Location.csv",
                "Dim_Time.csv",
                "Dim_Weather.csv",
                "Fact_Complaints.csv",
                "Fact_Energy.csv",
                "Fact_Pollution.csv",
                "Fact_Traffic.csv",
                "SecurityTable.csv",
                "Smart City Intelligence & Predictive Analytics.png",
                "Smart_City_Dashboard_Demo.mp4"
            ]
        },
        {
            "id": "public-transport",
            "name": "Public Transport Performance Analytics",
            "folder": "7. PowerBI_Public Transport Performance Analytics",
            "path": "7. PowerBI_Public Transport Performance Analytics",
            "viewer": "viewer.html?project=public-transport",
            "description": "Public transport analytics files for route performance, ridership trends, and service optimization dashboards.",
            "files": [
                "Passenger_Trends.csv",
                "Peak_Hours.csv",
                "Public Transport Performance Analytics In Sri Lanka.png",
                "Route_Congestion.csv",
                "Routes.csv",
                "Stops.csv",
                "Trips.csv"
            ]
        },
        {
            "id": "airline-dashboard",
            "name": "Airline Operations & Passenger Experience Dashboard",
            "folder": "8. PowerBI_Airline",
            "path": "8. PowerBI_Airline",
            "viewer": "viewer.html?project=airline-dashboard",
            "description": "Airline analytics dataset files and dashboard imagery for operational performance and customer experience reporting.",
            "files": [
                "Airline Operations & Passenger Experience Dashboard.png",
                "Airlines.csv",
                "Airport-download-hd-wallpapers.jpg",
                "Airports.csv",
                "DelayReasons.csv",
                "FlightRoutes.csv",
                "Flights.csv",
                "PassengerExperience.csv",
                "TimeDimension.csv"
            ]
        },
        {
            "id": "music-analytics",
            "name": "Music Analytics Dashboard",
            "folder": "9. music",
            "path": "9. music",
            "viewer": "viewer.html?project=music-analytics",
            "description": "Music dataset files, audio feature data, and visualization assets for analytics and mood detection.",
            "files": [
                "397756.jpg",
                "Audio/02 Abhi Toh Party Shuru Hui Hai.mp3",
                "Audio/03 - Sarsariya - DownloadMing.SE.mp3",
                "Audio/Alan Walker - Alone.mp3",
                "Audio/All Around The World.mp3",
                "Audio/All my people.mp3",
                "Audio/Anjaana - Atif Aslam.mp3",
                "Audio/Bheegi Bheegi.mp3",
                "Audio/Charlie_Puth_feat_Selena_Gomez_We_Dont_Talk_Anymore.mp3",
                "Audio/Cheap Thrills - Pitch Perfect 3 (Lyrics).mp3",
                "Audio/Cheap Thrills-sia .mp3",
                "Audio/Chris Brown - No Guidance (Audio) ft. Drake.mp3",
                "Audio/Chris Brown - Turn Up the Music.mp3",
                "Audio/Christina Aguilera - Loyal Brave True (From MulanOfficial Video).mp3",
                "Audio/Cinderella-Lavender's Blue.mp3",
                "Audio/Claydee Ft. Alex Velea - Hey Ma (Official Video).mp3",
                "Audio/Clean Bandit - Solo feat. Demi Lovato [Official Video].mp3",
                "Audio/Clean Bandit Mama (feat. Ellie Goulding) [Official Audio].mp3",
                "Audio/CNCO & Natti Natasha - Honey Boo (Official Video).mp3",
                "Audio/CNCOMeghanTrainorSeanPaulHeyDJRemixOfficialVideo-arabix - Copy.mp3",
                "Audio/Ed Sheeran - Shape Of You.mp3",
                "Audio/Gilehriyaan.mp3",
                "Audio/Hasi (Female).mp3",
                "Audio/Ishq Kamaal - Sadak 2.mp3",
                "Audio/Jab Koi.mp3",
                "Audio/Jeena Jeena.mp3",
                "Audio/Jeene Laga Hoon .mp3",
                "Audio/Jon Bellion - All Time Low (Audio).mp3",
                "Audio/Kabhi Alvida.mp3",
                "Audio/Kar Gayi Chull.mp3",
                "Audio/Keh Gayi Sorry - Jassie Gill.mp3",
                "Audio/Main Rang Sharbaton Ka.mp3",
                "Audio/Meri Aashiqui - Jubin Nautiyal.mp3",
                "Audio/Mitti Di Khushboo.mp3",
                "Audio/Nachde Ne Saare(MyMp3Song).mp3",
                "Audio/One Two Three Four - Get On The Dance Floor.mp3",
                "Audio/Raabta (kehte hain khuda) -Joy.mp3",
                "Audio/Sandawathiye___Ridma_Weerawardena___Charitha_Attalage.mp3",
                "Audio/SANUKA - Ciao Malli (චඕ මලල) Official Lyric Video.mp3",
                "Audio/Sanuka x Windy - Api Denna (අප දනන) Official Visualizer.mp3",
                "Audio/SANUKA_-_Sansara_Sihine_Official_Audio_WWW_SinhaWap_COM-57e6957b4325f.mp3",
                "Audio/Sanwedana සවදන (Lyrics) - Shane zing.mp3",
                "Audio/sarath sade(juliya).mp3",
                "Audio/Seda Mawatha - සද මවත - Hashani Wasana #DialogMusic.mp3",
                "Audio/See You Again Feat. Charlie Puth - (www.SongsLover.pk).mp3",
                "Audio/Seema Na - Abhisheka Wimalaweera.mp3",
                "Audio/SendMy Love to Your New Lover.mp3",
                "Audio/SeneheISURU AYESHMANTHA2019 New SongFull HD Music video.mp3",
                "Audio/Sepalikawo Shehan Kaushalya.mp3",
                "Audio/Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song).mp3",
                "Audio/Sharadha ( ශරධ ) - Lahiru Liyanage Official Video Yasas Medagedara.mp3",
                "Audio/Shashika Nisansala - Malsara Heesarin (Official Music Video).mp3",
                "Audio/Shawn_Mendes_&_Camila_Cabello_-_Senorita_-_(SongsLover.com).mp3",
                "Audio/Sheela Lyrics - Jaya Sri - lyrics ශල - ජය ශර.mp3",
                "Audio/Shehan Kaushalya - Mage Hithe www.my-free-mp3.net .mp3",
                "Audio/SHOBA (ශභ)Bhashi Devanga [Official Lyric Video 2019].mp3",
                "Audio/Sihilasee Official Video RUSH Uddika Premarathne Asanki De Silva Saranga Disasekara.mp3",
                "Audio/Taare Zameen Par.mp3",
                "Audio/Tamma Tamma Again.mp3",
                "Audio/Tenu Vekhi Jaavan - Shahid Mallya.mp3",
                "Audio/Tera Naam Doon.mp3",
                "Audio/Tere Bin - Atif Aslam.mp3",
                "Audio/tere sang.mp3",
                "Audio/The Chainsmokers– All We Know (feat. Phoebe Ryan).mp3",
                "Audio/The Vamps - All Night - MP3 320.mp3",
                "Audio/Tune Maari Entriyaan.mp3",
                "Audio/Woh Mere Bin - Atif Aslam.mp3",
                "Audio/Zaalima (Raees).mp3",
                "audio_ai_theme.json",
                "audio_features.csv",
                "audio_features_ai.csv",
                "ChatGPT Image Dec 23, 2025, 02_53_27 PM.png",
                "genre_mood_training.csv",
                "Live Audio Feature Extraction Dashboard.png"
            ]
        },
        {
            "id": "inventory-management",
            "name": "Inventory Management Dashboard",
            "folder": "10. Inventory_Management_Dashboard",
            "path": "10. Inventory_Management_Dashboard",
            "viewer": "viewer.html?project=inventory-management",
            "description": "Inventory analytics assets and dashboard files for stock tracking and supply chain reporting.",
            "files": [
                "inventory_management_dashboard.png",
                "inventory_management_dashboard.xlsx"
            ]
        },
        {
            "id": "crypto-analytics",
            "name": "Crypto Analytics Dashboard",
            "folder": "11. Crypto",
            "path": "11. Crypto",
            "viewer": "viewer.html?project=crypto-analytics",
            "description": "Cryptocurrency market dataset and dashboard imagery for pricing and portfolio analytics.",
            "files": [
                "Crypto_Dashboard.png",
                "ID,Symbol,Name,Price,MarketCap,Volu.csv",
                "ID,Symbol,Name,Price,MarketCap,Volu.txt",
                "Video Project 4.mp4"
            ]
        },
        {
            "id": "finsight",
            "name": "FinSight Dashboard",
            "folder": "12. FinSight",
            "path": "12. FinSight",
            "viewer": "viewer.html?project=finsight",
            "description": "Financial analytics dashboard files and presentation assets for savings and portfolio insight.",
            "files": [
                "Finsight_Dashboard_Demo.mp4",
                "Sanduni_Ranawake_FinSightAssessment_Dashboard.png",
                "Sanduni_Ranawake_FinSightAssessment_Presentation.pdf",
                "Sanduni_Ranawake_FinSightAssessment_Presentation.pptx"
            ]
        },
        {
            "id": "intelligent-invoice-pipeline",
            "name": "Intelligent Invoice Pipeline",
            "folder": "13. intelligent_invoice_pipeline",
            "path": "13. intelligent_invoice_pipeline",
            "viewer": "viewer.html?project=intelligent-invoice-pipeline",
            "description": "Automated invoice processing project with OCR, validation rules, and operational workflow assets.",
            "files": [
                "$null",
                ".env",
                ".env.example",
                ".gitignore",
                "1. Intelligent_Invoice_Pipeline.pdf",
                "2. Invoice_demo.mp4",
                "__pycache__/run_pipeline.cpython-310.pyc",
                "ASSESSMENT_READY.md",
                "AUTO_CLEANUP_FIX.md",
                "CHEAT_SHEET.md",
                "COMPLETE_SOLUTION_SUMMARY.md",
                "dashboard/__init__.py",
                "dashboard/app.py",
                "dashboard/templates/admin.html",
                "dashboard/templates/index.html",
                "DASHBOARD_DISPLAY_READY.md",
                "data/__init__.py",
                "data/__pycache__/__init__.cpython-310.pyc",
                "data/__pycache__/__init__.cpython-312.pyc",
                "data/__pycache__/storage.cpython-310.pyc",
                "data/__pycache__/storage.cpython-312.pyc",
                "data/invoices.db",
                "data/storage.py",
                "DATABASE_CLEANUP_FIX.md",
                "DATABASE_CLEANUP_SOLUTION.md",
                "DEMO_COMMANDS.md",
                "DESIGN.md",
                "docker-compose.yml",
                "docker_logs.txt",
                "Dockerfile",
                "DUPLICATES_CLEANUP.md",
                "extraction/__init__.py",
                "extraction/__pycache__/__init__.cpython-310.pyc",
                "extraction/__pycache__/field_extractor.cpython-310.pyc",
                "extraction/field_extractor.py",
                "FRESH_START_CHECKLIST.md",
                "FRESH_START_WORKFLOW.md",
                "IMPLEMENTATION_SUMMARY.md",
                "import sqlite3.py",
                "INDEX.md",
                "ingestion/__init__.py",
                "ingestion/__pycache__/__init__.cpython-310.pyc",
                "ingestion/__pycache__/email_ingestor.cpython-310.pyc",
                "ingestion/email_ingestor.py",
                "logs/invoice_001_acme_raw.txt",
                "logs/invoice_002_globaltech_raw.txt",
                "logs/invoice_003_missing_date_raw.txt",
                "logs/invoice_004_duplicate_raw.txt",
                "logs/invoice_005_highvalue_raw.txt",
                "logs/pipeline.log",
                "ocr/__init__.py",
                "ocr/__pycache__/__init__.cpython-310.pyc",
                "ocr/__pycache__/pdf_extractor.cpython-310.pyc",
                "ocr/pdf_extractor.py",
                "OLD_DATA_CLEANUP_FIX.md",
                "PROJECT_STATUS.md",
                "QUICK_GUIDE.md",
                "QUICK_REFERENCE.md",
                "QUICK_START.md",
                "README.md",
                "requirements.txt",
                "routing/__init__.py",
                "routing/__pycache__/__init__.cpython-310.pyc",
                "routing/__pycache__/router.cpython-310.pyc",
                "routing/router.py",
                "routing/rules.yaml",
                "run_pipeline.py",
                "sample_invoices/invoice_001_acme.pdf",
                "sample_invoices/invoice_002_globaltech.pdf",
                "sample_invoices/invoice_003_missing_date.pdf",
                "sample_invoices/invoice_004_duplicate.pdf",
                "sample_invoices/invoice_005_highvalue.pdf",
                "scripts/backfill_filenames.py",
                "scripts/check_db.py",
                "scripts/check_ids.py",
                "scripts/clean_to_5_invoices.py",
                "scripts/cleanup_duplicates.py",
                "scripts/dashboard_display.py",
                "scripts/db_cli.py",
                "scripts/delete_db.py",
                "scripts/display_invoices.py",
                "scripts/git_commit.py",
                "scripts/http_check.py",
                "scripts/inspect_dups.py",
                "scripts/list_invoices.py",
                "scripts/query_invoice.py",
                "scripts/quickstart.py",
                "scripts/README.md",
                "scripts/remove_duplicates.py",
                "scripts/reset_database.py",
                "scripts/restore_filename.py",
                "scripts/seed_sample_data.py",
                "scripts/show_stats.py",
                "scripts/test_pipeline.py",
                "SOLUTION_COMPLETE.md",
                "TECHNICAL_ASSESSMENT.md",
                "TEST_DATA_GUIDE.md",
                "TEST_DATA_VERIFICATION.md",
                "validation/__init__.py",
                "validation/__pycache__/__init__.cpython-310.pyc",
                "validation/__pycache__/validator.cpython-310.pyc",
                "validation/validator.py"
            ]
        }
    ],
    "certificates": [
        {
            "id": "rusl-innerbit",
            "name": "RUSL Innerbit Project Carnival 2026",
            "folder": "certificates/rusl-innerbit",
            "path": "../certificates/rusl-innerbit",
            "link": "../certificates/rusl-innerbit/",
            "description": "Project certificate folder for the RUSL Innerbit Project Carnival.",
            "files": []
        },
        {
            "id": "ux-design",
            "name": "UX Design Certificates",
            "folder": "certificates/ux-design",
            "path": "../certificates/ux-design",
            "link": "../certificates/ux-design/",
            "description": "UX design certificates and documentation folders.",
            "files": [
                "1_UX/UX PROCESS.docx",
                "1_UX/UX PROCESS.pdf",
                "2_UI/WHAT IS USER INTERFACE AND HOW IS IT DIFFERENT FROM UX.docx",
                "Certificates_UX_Microsoft/UX_MS.pdf",
                "UX_Microsoft/What is UX.docx"
            ]
        },
        {
            "id": "data-science",
            "name": "Data Science Certificates",
            "folder": "certificates/data-science",
            "path": "../certificates/data-science",
            "link": "../certificates/data-science/",
            "description": "Data science certification documents folder.",
            "files": []
        },
        {
            "id": "power-automate",
            "name": "Power Automate Certificates",
            "folder": "certificates/power-automate",
            "path": "../certificates/power-automate",
            "link": "../certificates/power-automate/",
            "description": "Power Automate certification documents.",
            "files": [
                "Achievements - sanduniranawake-5854 _ Microsoft Learn.pdf",
                "Automate_Input_Output.pdf"
            ]
        },
        {
            "id": "cyber-security",
            "name": "Cyber Security Certificate",
            "folder": "certificates/cyber-security",
            "path": "../certificates/cyber-security",
            "link": "../certificates/cyber-security/",
            "description": "Cyber security certification document folder.",
            "files": [
                "Introduction_to_Cybersecurity_certificate_sanduniranawake4-gmail-com_d58a943a-9cc7-46c0-af79-017ac1eb5a33.pdf"
            ]
        }
    ]
};
