#!/usr/bin/env python3
import os
import json
import sys

# Config
PROJECTS_DIR = os.path.dirname(os.path.abspath(__file__))
DIR_INDEX = os.path.join(PROJECTS_DIR, 'dirIndex.json')
OUT_FILE = os.path.join(PROJECTS_DIR, 'fileData.js')
# Extensions to inline (text-based)
TEXT_EXTS = {'.md', '.txt', '.csv', '.json', '.js', '.py', '.html', '.css', '.xml', '.sql', '.sh', '.bash'}
# Max bytes to inline per file (avoid huge files)
MAX_BYTES = 200 * 1024  # 200 KB


def slug_from_folder(folder_name):
    # remove leading numbers and dot, then slugify
    import re
    s = re.sub(r'^\s*\d+\.?\s*', '', folder_name)
    s = re.sub(r'[_\s]+', '-', s)
    s = re.sub(r'[^0-9a-zA-Z-]+', '', s)
    s = re.sub(r'-{2,}', '-', s)
    return s.lower()


def safe_read(path):
    try:
        size = os.path.getsize(path)
        if size > MAX_BYTES:
            return None
        with open(path, 'r', encoding='utf-8', errors='replace') as f:
            return f.read()
    except Exception:
        return None


def main():
    if not os.path.exists(DIR_INDEX):
        print('dirIndex.json not found in', PROJECTS_DIR)
        sys.exit(1)
    with open(DIR_INDEX, 'r', encoding='utf-8') as f:
        index = json.load(f)

    file_data = {}

    for folder, files in index.items():
        folder_key = folder
        folder_slug = slug_from_folder(folder)
        file_data.setdefault(folder_key, {})
        file_data.setdefault(folder_slug, {})
        for fname in files:
            _, ext = os.path.splitext(fname)
            ext = ext.lower()
            if ext in TEXT_EXTS:
                # build absolute path
                abs_path = os.path.join(PROJECTS_DIR, folder, fname)
                if os.path.exists(abs_path):
                    content = safe_read(abs_path)
                    if content is not None:
                        # store under both raw filename and encoded filename variant
                        file_data[folder_key].setdefault(fname, content)
                        file_data[folder_slug].setdefault(fname, content)

    # write output JS
    with open(OUT_FILE, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by generate_file_data.py\n')
        f.write('window.fileData = ')
        json.dump(file_data, f, ensure_ascii=False, indent=2)
        f.write(';\n')

    print('Wrote', OUT_FILE)


if __name__ == '__main__':
    main()
